name: buildx

on:
  push:
    branches:
      - 'master'

env:
  DOCKERHUB_USER: knw1234
  IMAGE_NAME: knw1234/blog-back

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to docker.io
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Buildx and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.VER_FULL }}
            ${{ env.IMAGE_NAME }}:${{ env.VER_MINOR }}
            ${{ env.IMAGE_NAME }}:${{ env.VER_MAJOR }}
          platforms: linux/amd64,linux/arm64
          push: true
      -
        name: Update Dockerhub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          repository: ${{ env.IMAGE_NAME }}
          short-description: ${{ steps.vars.outputs.github_desc }}
